# Generated by Django 2.1 on 2018-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('violence_scale', models.IntegerField(default=5)),
                ('horror_scale', models.IntegerField(default=5)),
                ('blood_scale', models.IntegerField(default=5)),
                ('alcohol_drugs_scale', models.IntegerField(default=5)),
                ('abusive_language_scale', models.IntegerField(default=5)),
                ('sex_nudity_scale', models.IntegerField(default=5)),
                ('sensetive_religious_scale', models.IntegerField(default=5)),
                ('racism_scale', models.IntegerField(default=5)),
                ('overall_child_friendliness_scale', models.IntegerField(default=5)),
                ('user_comments', models.CharField(default='Something else which can bother children?', max_length=2000)),
            ],
        ),
    ]
